spring:
  datasource:
    url: jdbc:mysql://10.6.253.207:3306/test
    username: root
    password: 123
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
## 因为我们使用的是mybatis 的注解，所以可以省略
#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.shiro.springboot.entity  # 注意：对应实体类的路径
logging:
  level: TRACE
debug: true
